spring:
    profiles:
        active: @profileActive@
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
    messages:
      encoding: UTF-8

## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.xj.ptgd.entity.body  # 注意：对应mapper.xml实体类的路径



